/* DPRO Health — bloodwork marker reference
   ------------------------------------------------------------------
   One entry per marker. Fields:
     id        stable key
     name      display name
     cat       category key (see CATS)
     unit      canonical unit the ranges below are expressed in
     alt       alternate units -> multiply-by factor to reach canonical unit
     aliases   strings that identify the marker on a lab report (case-insensitive, longest wins)
     std       standard lab reference range {m:[lo,hi], f:[lo,hi]} or {all:[lo,hi]}
     opt       DPRO optimal range, same shape. null bound = open-ended.
     kind      'range' (both bounds matter) | 'lower' (lower is better) | 'higher' (higher is better)
     high/low  what a value outside/above optimal tends to suggest (educational, not diagnostic)
     levers    what commonly moves the marker
   Standard ranges follow common US lab conventions (LabCorp / Quest, adult). Optimal ranges are
   DPRO Health targets for healthy, active adults and are DRAFT until David signs off.
   None of this is medical advice. */
window.BW_CATS = [
  ['hormones','Hormones'],['thyroid','Thyroid'],['metabolic','Blood sugar & insulin'],['lipids','Lipids'],
  ['liver','Liver'],['kidney','Kidney'],['lytes','Electrolytes & minerals'],['cbc','Complete blood count'],
  ['iron','Iron'],['inflam','Inflammation'],['vitamins','Vitamins'],['other','Other']
];
window.BW_MARKERS = [
/* ---------------- HORMONES ---------------- */
{id:'testosterone_total',name:'Testosterone, Total',cat:'hormones',unit:'ng/dL',alt:{'nmol/L':28.84},
 aliases:['Testosterone, Total, LC/MS','Testosterone,Total,LC/MS','Testosterone, Total','Testosterone,Total','Total Testosterone','Testosterone Total','Testosterone'],
 std:{m:[264,916],f:[15,70]},opt:{m:[700,1000],f:[35,70]},kind:'range',
 high:'Above range usually means exogenous testosterone or a lab timing quirk; very high natural values are rare.',
 low:'Low total T is the classic driver of fatigue, low libido, poor recovery and stubborn body fat. Confirm with a second morning draw before acting.',
 levers:'Sleep, body fat, resistance training, zinc/vitamin D status, alcohol, medication review. Clinically: TRT, enclomiphene, HCG.'},
{id:'testosterone_free',name:'Testosterone, Free',cat:'hormones',unit:'pg/mL',alt:{'ng/dL':10},
 aliases:['Free Testosterone(Direct)','Free Testosterone (Direct)','Testosterone, Free','Testosterone,Free','Free Testosterone','Testosterone Free'],
 std:{m:[8.7,25.1],f:[0.0,4.2]},opt:{m:[18,30],f:[1.5,4.2]},kind:'range',
 high:'High free T alongside normal total T points to low SHBG.',
 low:'Free T is what tissues actually use. Low free T with normal total T means SHBG is binding too much of it.',
 levers:'Lower SHBG (boron, lower thyroid overdrive, insulin normalization), raise total T. Direct-RIA and calculated methods give different numbers — compare like with like.'},
{id:'shbg',name:'SHBG',cat:'hormones',unit:'nmol/L',
 aliases:['Sex Horm Binding Glob, Serum','Sex Hormone Binding Globulin','Sex Horm Binding Glob','SHBG'],
 std:{m:[16.5,55.9],f:[24.6,122]},opt:{m:[20,40],f:[40,90]},kind:'range',
 high:'High SHBG locks up testosterone. Common with low calories, high thyroid output, liver stress, or aging.',
 low:'Low SHBG often travels with insulin resistance and higher body fat.',
 levers:'Insulin sensitivity, body composition, thyroid balance, boron, adequate calories.'},
{id:'estradiol',name:'Estradiol',cat:'hormones',unit:'pg/mL',alt:{'pmol/L':0.2724},
 aliases:['Estradiol, Sensitive','Estradiol,Sensitive','Estradiol Sensitive','Estradiol (Sensitive)','Estradiol'],
 std:{m:[8,35],f:[15,350]},opt:{m:[20,35],f:null},kind:'range',
 high:'In men, high E2 (especially on TRT) can mean water retention, mood swings and nipple sensitivity. In women, interpret against cycle phase.',
 low:'Too-low E2 in men costs libido, joint comfort, bone density and mood — crashing it with an AI is a common mistake.',
 levers:'Body fat, alcohol, TRT dose/frequency; aromatase inhibitors only when symptomatic and confirmed on a sensitive assay.'},
{id:'dht',name:'DHT',cat:'hormones',unit:'ng/dL',
 aliases:['Dihydrotestosterone','DHT'],
 std:{m:[30,85],f:[4,22]},opt:{m:[40,85],f:null},kind:'range',
 high:'High DHT can accelerate hair loss and acne in the genetically prone; otherwise not usually a problem.',
 low:'Low DHT can blunt libido and drive; often seen on 5-alpha-reductase inhibitors.',
 levers:'Testosterone level, 5-AR inhibitors (finasteride/dutasteride), creatine (mild).'},
{id:'lh',name:'LH',cat:'hormones',unit:'mIU/mL',
 aliases:['Luteinizing Hormone','LH, Serum','LH'],
 std:{m:[1.7,8.6],f:[1.0,12.6]},opt:{m:[3,8],f:null},kind:'range',
 high:'High LH with low T means the testes aren\'t responding (primary hypogonadism).',
 low:'Low or suppressed LH with low T points to the pituitary/brain — or to exogenous testosterone shutting the axis down.',
 levers:'Exogenous androgens suppress it; enclomiphene/clomiphene and HCG protocols raise or replace it.'},
{id:'fsh',name:'FSH',cat:'hormones',unit:'mIU/mL',
 aliases:['Follicle Stimulating Hormone','FSH, Serum','FSH'],
 std:{m:[1.5,12.4],f:[1.5,12.4]},opt:{m:[2,8],f:null},kind:'range',
 high:'High FSH in men suggests reduced sperm production; in women it rises approaching menopause.',
 low:'Suppressed FSH is expected on TRT or other exogenous androgens.',
 levers:'Same axis as LH — exogenous hormones suppress; SERMs and HCG-based protocols restore.'},
{id:'prolactin',name:'Prolactin',cat:'hormones',unit:'ng/mL',
 aliases:['Prolactin'],
 std:{m:[4.0,15.2],f:[4.8,23.3]},opt:{m:[5,12],f:[5,18]},kind:'range',
 high:'High prolactin suppresses testosterone and libido. Mild elevations come from stress, sleep loss or some medications; large ones need a prolactinoma ruled out.',
 low:'Low prolactin is rarely an issue; sometimes seen with dopamine agonists.',
 levers:'Sleep, stress, dopamine-affecting meds; vitamin B6, P5P; clinically cabergoline.'},
{id:'dheas',name:'DHEA-Sulfate',cat:'hormones',unit:'µg/dL',
 aliases:['DHEA-Sulfate','DHEA Sulfate','DHEA-S','DHEAS'],
 std:{m:[100,450],f:[50,300]},opt:{m:[250,450],f:[150,300]},kind:'range',
 high:'High DHEA-S can come from supplementation or, in women, PCOS/adrenal causes.',
 low:'Low DHEA-S tracks with adrenal fatigue patterns, chronic stress and aging; it declines steadily after 30.',
 levers:'Stress load, sleep, DHEA supplementation (small doses, retest).'},
{id:'cortisol',name:'Cortisol (AM)',cat:'hormones',unit:'µg/dL',alt:{'nmol/L':0.03625},
 aliases:['Cortisol - AM','Cortisol, AM','Cortisol AM','Cortisol'],
 std:{all:[6.2,19.4]},opt:{all:[10,18]},kind:'range',
 high:'High morning cortisol reflects stress, poor sleep, overtraining or under-eating; chronically high erodes muscle and drives central fat.',
 low:'Low morning cortisol suggests a blunted stress axis — often chronic stress that has burned out, or recent steroid use.',
 levers:'Sleep, training volume, calorie sufficiency, caffeine timing, stress management. Draw between 7–9 AM.'},
{id:'progesterone',name:'Progesterone',cat:'hormones',unit:'ng/mL',
 aliases:['Progesterone'],
 std:{m:[0.0,0.5],f:[0.1,25]},opt:{m:null,f:null},kind:'range',
 high:'In women, high progesterone is expected in the luteal phase; in men it is rare and usually medication-related.',
 low:'In women, low luteal progesterone can mean short or irregular cycles; interpret with cycle day.',
 levers:'Cycle phase, stress, body fat; clinically bioidentical progesterone.'},
{id:'igf1',name:'IGF-1',cat:'hormones',unit:'ng/mL',
 aliases:['Insulin-Like Growth Factor I','Insulin Like Growth Factor 1','IGF-1','IGF1','IGF 1'],
 std:{all:[70,250]},opt:{all:[180,250]},kind:'range',
 high:'High IGF-1 usually means GH secretagogues or GH; sustained very high levels carry long-term risk.',
 low:'Low IGF-1 reflects low growth hormone output — poor recovery, thin skin, low muscle. Also drops with under-eating.',
 levers:'Sleep quality, protein intake, GH secretagogues (CJC/Ipamorelin, tesamorelin), body fat. Age-adjusted ranges matter.'},
/* ---------------- THYROID ---------------- */
{id:'tsh',name:'TSH',cat:'thyroid',unit:'µIU/mL',
 aliases:['Thyroid Stimulating Hormone','TSH'],
 std:{all:[0.45,4.5]},opt:{all:[0.5,2.0]},kind:'range',
 high:'High TSH means the brain is pushing a sluggish thyroid — fatigue, cold, weight gain, hair thinning. Above ~2.5 is worth a full panel.',
 low:'Low TSH suggests too much thyroid hormone (over-medication or hyperthyroidism) — or a suppressed axis.',
 levers:'Iodine/selenium/iron status, calorie deficit depth, sleep; clinically levothyroxine or T3.'},
{id:'ft4',name:'Free T4',cat:'thyroid',unit:'ng/dL',alt:{'pmol/L':0.0777},
 aliases:['T4,Free(Direct)','T4, Free (Direct)','T4, Free','T4,Free','Free T4','Thyroxine (T4) Free','Free Thyroxine','FT4'],
 std:{all:[0.82,1.77]},opt:{all:[1.2,1.7]},kind:'range',
 high:'High free T4 with low TSH is hyperthyroid territory or over-replacement.',
 low:'Low free T4 is the storage hormone running short — the thyroid itself is under-producing.',
 levers:'Iodine, selenium, tyrosine, calorie sufficiency; clinically T4 replacement.'},
{id:'ft3',name:'Free T3',cat:'thyroid',unit:'pg/mL',alt:{'pmol/L':0.651},
 aliases:['Triiodothyronine (T3), Free','Triiodothyronine,Free,Serum','Triiodothyronine, Free','T3, Free','T3,Free','Free T3','FT3'],
 std:{all:[2.0,4.4]},opt:{all:[3.2,4.2]},kind:'range',
 high:'High free T3 drives a racing heart, anxiety and muscle loss — usually over-medication with T3.',
 low:'Free T3 is the active hormone. Low-normal T3 with normal TSH is the classic "labs are fine but I feel slow" pattern — common in hard dieting.',
 levers:'Carbohydrate intake, calorie deficit depth, selenium, zinc, sleep; clinically liothyronine.'},
{id:'rt3',name:'Reverse T3',cat:'thyroid',unit:'ng/dL',
 aliases:['Reverse T3, Serum','Reverse T3','rT3','T3, Reverse'],
 std:{all:[9.2,24.1]},opt:{all:[9,18]},kind:'lower',
 high:'High reverse T3 means T4 is being shunted into an inactive form — stress, illness, deep deficits, or inflammation.',
 low:'Low rT3 is not a concern.',
 levers:'Reduce deficit/stress, treat inflammation, adequate carbs; T3-only protocols in some cases.'},
{id:'tpo',name:'TPO Antibodies',cat:'thyroid',unit:'IU/mL',
 aliases:['Thyroid Peroxidase (TPO) Ab','Thyroid Peroxidase Antibodies','TPO Antibodies','TPO Ab','Thyroperoxidase'],
 std:{all:[0,34]},opt:{all:[0,9]},kind:'lower',
 high:'Elevated TPO antibodies indicate autoimmune thyroid activity (Hashimoto\'s) even when TSH is still normal.',
 low:'Undetectable is ideal.',
 levers:'Selenium, vitamin D, gluten trial in some, gut health; monitor TSH over time.'},
{id:'t3_total',name:'T3, Total',cat:'thyroid',unit:'ng/dL',
 aliases:['Triiodothyronine (T3)','T3, Total','Total T3','T3 Total'],
 std:{all:[71,180]},opt:{all:[110,170]},kind:'range',
 high:'High total T3 tracks with hyperthyroidism or over-replacement.',
 low:'Low total T3 mirrors low free T3 — poor conversion or under-production.',
 levers:'Same as free T3.'},
/* ---------------- METABOLIC ---------------- */
{id:'glucose',name:'Glucose (fasting)',cat:'metabolic',unit:'mg/dL',alt:{'mmol/L':18.016},
 aliases:['Glucose, Serum','Glucose, Plasma','Glucose Fasting','Fasting Glucose','Glucose'],
 std:{all:[70,99]},opt:{all:[75,90]},kind:'range',
 high:'Fasting glucose in the 100s is pre-diabetic territory; one high reading can also be a stressful morning or a non-fasted draw.',
 low:'Low fasting glucose is usually fine in lean, fasted people; symptomatic lows need a look at insulin and meds.',
 levers:'Carb quality/timing, body fat, sleep, resistance training, walking after meals; GLP-1s, metformin, berberine.'},
{id:'a1c',name:'Hemoglobin A1c',cat:'metabolic',unit:'%',
 aliases:['Hemoglobin A1c','Hemoglobin A1C','HbA1c','HbA1C','A1c','A1C'],
 std:{all:[4.8,5.6]},opt:{all:[4.8,5.3]},kind:'range',
 high:'A1c reflects ~3 months of average glucose. 5.7–6.4 is pre-diabetes, 6.5+ is diabetes range.',
 low:'Very low A1c is usually fine; can be skewed by anemia or high red-cell turnover.',
 levers:'Same levers as glucose, plus GLP-1 therapy. Note anemia and altitude distort A1c.'},
{id:'insulin',name:'Insulin (fasting)',cat:'metabolic',unit:'µIU/mL',
 aliases:['Insulin, Fasting','Insulin Fasting','Fasting Insulin','Insulin'],
 std:{all:[2.6,24.9]},opt:{all:[2,6]},kind:'range',
 high:'High fasting insulin is the earliest sign of insulin resistance — years before glucose moves. Fat loss gets much harder here.',
 low:'Very low insulin with high glucose warrants a medical look (beta-cell function).',
 levers:'Body fat, carb load, fiber, sleep, strength training, walking; GLP-1s, metformin, berberine.'},
{id:'homa_ir',name:'HOMA-IR',cat:'metabolic',unit:'',computed:['glucose','insulin'],
 aliases:['HOMA-IR','HOMA IR'],
 std:{all:[0,2.5]},opt:{all:[0,1.0]},kind:'lower',
 high:'HOMA-IR above ~2 indicates insulin resistance; above 1 is already sub-optimal for an athlete.',
 low:'Lower is better.',
 levers:'Computed from fasting glucose × insulin ÷ 405. Improve either input.'},
{id:'uric',name:'Uric Acid',cat:'metabolic',unit:'mg/dL',alt:{'µmol/L':0.01681},
 aliases:['Uric Acid, Serum','Uric Acid'],
 std:{m:[3.7,8.6],f:[2.5,7.1]},opt:{all:[3.5,5.5]},kind:'range',
 high:'High uric acid tracks with fructose/alcohol intake, insulin resistance and gout risk; dehydration and hard dieting spike it.',
 low:'Low uric acid is rarely a problem.',
 levers:'Fructose/alcohol, hydration, weight, tart cherry; allopurinol when clinically needed.'},
/* ---------------- LIPIDS ---------------- */
{id:'chol',name:'Cholesterol, Total',cat:'lipids',unit:'mg/dL',alt:{'mmol/L':38.67},
 aliases:['Cholesterol, Total','Cholesterol,Total','Total Cholesterol','Cholesterol Total'],
 std:{all:[100,199]},opt:{all:[150,220]},kind:'range',
 high:'Total cholesterol alone says little — look at ApoB, LDL, triglycerides and HDL together.',
 low:'Very low total cholesterol can go with low hormone production and low energy; often a sign of under-eating.',
 levers:'Saturated fat, fiber, weight, thyroid status; statins/ezetimibe when risk warrants.'},
{id:'ldl',name:'LDL Cholesterol',cat:'lipids',unit:'mg/dL',alt:{'mmol/L':38.67},
 aliases:['LDL Chol Calc (NIH)','LDL Cholesterol Calc','LDL-Cholesterol','LDL Cholesterol','LDL Chol','LDL-C','LDL'],
 std:{all:[0,99]},opt:{all:[0,90]},kind:'lower',
 high:'High LDL raises long-term cardiovascular risk; anabolic use and keto-style diets push it up. Confirm with ApoB.',
 low:'Lower is generally better for the heart; extremely low values are usually medication-driven.',
 levers:'Saturated fat, soluble fiber, weight, plant sterols; statins, ezetimibe, PCSK9 when indicated.'},
{id:'hdl',name:'HDL Cholesterol',cat:'lipids',unit:'mg/dL',alt:{'mmol/L':38.67},
 aliases:['HDL Cholesterol','HDL-Cholesterol','HDL-C','HDL'],
 std:{m:[40,200],f:[50,200]},opt:{m:[50,90],f:[60,100]},kind:'range',
 high:'Very high HDL is usually fine; extreme values can be genetic.',
 low:'Low HDL travels with insulin resistance, smoking, inactivity and oral anabolics (which crush it).',
 levers:'Cardio, weight loss, omega-3s, alcohol moderation, avoiding oral androgens.'},
{id:'tg',name:'Triglycerides',cat:'lipids',unit:'mg/dL',alt:{'mmol/L':88.57},
 aliases:['Triglycerides','Triglyceride','Trig'],
 std:{all:[0,149]},opt:{all:[0,80]},kind:'lower',
 high:'High triglycerides are the fastest lipid to respond to diet — sugar, alcohol, excess calories and insulin resistance.',
 low:'Lower is better.',
 levers:'Sugar/alcohol, refined carbs, omega-3s (2–4 g EPA/DHA), weight loss, fasting before the draw.'},
{id:'nonhdl',name:'Non-HDL Cholesterol',cat:'lipids',unit:'mg/dL',
 aliases:['Non-HDL Cholesterol','Non HDL Cholesterol','Non-HDL Chol','Non-HDL'],
 std:{all:[0,129]},opt:{all:[0,110]},kind:'lower',
 high:'Non-HDL captures all the atherogenic particles; treat like LDL.',
 low:'Lower is better.',
 levers:'Same as LDL and triglycerides.'},
{id:'vldl',name:'VLDL Cholesterol',cat:'lipids',unit:'mg/dL',
 aliases:['VLDL Cholesterol Cal','VLDL Cholesterol','VLDL'],
 std:{all:[5,40]},opt:{all:[5,20]},kind:'range',
 high:'High VLDL mirrors high triglycerides.',
 low:'Not a concern.',
 levers:'Same as triglycerides.'},
{id:'apob',name:'Apolipoprotein B',cat:'lipids',unit:'mg/dL',
 aliases:['Apolipoprotein B','Apo B','ApoB'],
 std:{all:[0,90]},opt:{all:[0,70]},kind:'lower',
 high:'ApoB counts the actual number of atherogenic particles — the best single lipid predictor. Above 90 is worth acting on; above 110 is high risk.',
 low:'Lower is better.',
 levers:'Same as LDL; ApoB is what to track when treating.'},
{id:'lpa',name:'Lipoprotein (a)',cat:'lipids',unit:'nmol/L',alt:{'mg/dL':2.5},
 aliases:['Lipoprotein (a)','Lipoprotein(a)','Lp(a)','LP(a)'],
 std:{all:[0,75]},opt:{all:[0,75]},kind:'lower',
 high:'Lp(a) is genetic and barely moves with lifestyle. High Lp(a) means being stricter with everything else (ApoB, blood pressure, glucose).',
 low:'Low is ideal. Test once — it does not change much.',
 levers:'Mostly genetic; niacin modestly, PCSK9 inhibitors; new drugs in trials.'},
{id:'tg_hdl',name:'TG / HDL ratio',cat:'lipids',unit:'',computed:['tg','hdl'],
 aliases:['TG/HDL','Triglyceride/HDL'],
 std:{all:[0,3.0]},opt:{all:[0,1.5]},kind:'lower',
 high:'A high TG/HDL ratio is a cheap proxy for insulin resistance and small dense LDL.',
 low:'Lower is better.',
 levers:'Computed from triglycerides ÷ HDL.'},
{id:'chol_hdl',name:'Cholesterol / HDL ratio',cat:'lipids',unit:'',
 aliases:['Chol/HDL Ratio','Chol/HDL','Cholesterol/HDL Ratio','Total Cholesterol/HDL'],
 std:{all:[0,5.0]},opt:{all:[0,3.5]},kind:'lower',
 high:'Higher ratio, higher risk.',
 low:'Lower is better.',
 levers:'Raise HDL, lower total cholesterol.'},
/* ---------------- LIVER ---------------- */
{id:'alt',name:'ALT',cat:'liver',unit:'U/L',alt:{'IU/L':1},
 aliases:['ALT (SGPT)','ALT(SGPT)','Alanine Aminotransferase','SGPT','ALT'],
 std:{m:[0,44],f:[0,32]},opt:{all:[10,30]},kind:'range',
 high:'High ALT is the liver signalling stress — fatty liver, alcohol, oral anabolics, some supplements, or a hard leg session in the prior 72 hours.',
 low:'Low ALT is fine; very low can hint at B6 deficiency.',
 levers:'Alcohol, body fat, fructose, oral androgens, hard training before the draw; TUDCA, NAC, coffee.'},
{id:'ast',name:'AST',cat:'liver',unit:'U/L',alt:{'IU/L':1},
 aliases:['AST (SGOT)','AST(SGOT)','Aspartate Aminotransferase','SGOT','AST'],
 std:{all:[0,40]},opt:{all:[10,30]},kind:'range',
 high:'AST rises with liver stress but also with muscle damage — lifters routinely run it high after training. Compare with GGT and CK.',
 low:'Not a concern.',
 levers:'Rest 72 hours before the draw, alcohol, oral androgens, body fat.'},
{id:'alp',name:'Alkaline Phosphatase',cat:'liver',unit:'U/L',alt:{'IU/L':1},
 aliases:['Alkaline Phosphatase','Alk Phos','ALP'],
 std:{all:[44,121]},opt:{all:[50,100]},kind:'range',
 high:'High ALP can come from bone turnover (growth, healing fractures) or bile-duct issues.',
 low:'Low ALP sometimes reflects zinc or magnesium deficiency, or hypothyroidism.',
 levers:'Zinc, magnesium, thyroid status; evaluate bile flow if high with GGT.'},
{id:'ggt',name:'GGT',cat:'liver',unit:'U/L',alt:{'IU/L':1},
 aliases:['Gamma-Glutamyl Transferase','Gamma Glutamyl Transferase','GGT'],
 std:{m:[0,65],f:[0,60]},opt:{all:[0,25]},kind:'lower',
 high:'GGT is the most sensitive marker for alcohol and oxidative stress on the liver; also rises with fatty liver.',
 low:'Lower is better.',
 levers:'Alcohol, body fat, NAC/glycine (glutathione support), coffee.'},
{id:'bili',name:'Bilirubin, Total',cat:'liver',unit:'mg/dL',alt:{'µmol/L':0.05848},
 aliases:['Bilirubin, Total','Bilirubin Total','Total Bilirubin','Bilirubin'],
 std:{all:[0.0,1.2]},opt:{all:[0.3,1.2]},kind:'range',
 high:'Mildly high bilirubin is often benign Gilbert\'s syndrome (fasting makes it worse); larger rises need liver/bile evaluation.',
 low:'Not a concern.',
 levers:'Fasting length before the draw, liver health.'},
{id:'albumin',name:'Albumin',cat:'liver',unit:'g/dL',alt:{'g/L':0.1},
 aliases:['Albumin, Serum','Albumin'],
 std:{all:[3.8,4.9]},opt:{all:[4.2,4.9]},kind:'range',
 high:'High albumin usually just means dehydration at the draw.',
 low:'Low albumin points to under-eating protein, inflammation, or liver/kidney issues.',
 levers:'Protein intake, inflammation, hydration.'},
{id:'protein',name:'Protein, Total',cat:'liver',unit:'g/dL',alt:{'g/L':0.1},
 aliases:['Protein, Total','Total Protein','Protein Total'],
 std:{all:[6.0,8.5]},opt:{all:[6.5,8.0]},kind:'range',
 high:'High total protein is usually dehydration or chronic inflammation raising globulins.',
 low:'Low total protein tracks with low albumin — nutrition, absorption, liver.',
 levers:'Protein intake, hydration, inflammation.'},
{id:'globulin',name:'Globulin, Total',cat:'liver',unit:'g/dL',
 aliases:['Globulin, Total','Globulin Total','Globulin'],
 std:{all:[1.5,4.5]},opt:{all:[2.0,3.2]},kind:'range',
 high:'High globulin suggests chronic immune activation or inflammation.',
 low:'Low globulin can reflect immune suppression or protein loss.',
 levers:'Address inflammation and immune stressors.'},
{id:'ag_ratio',name:'A/G Ratio',cat:'liver',unit:'',
 aliases:['A/G Ratio','Albumin/Globulin Ratio','Albumin/Globulin'],
 std:{all:[1.2,2.2]},opt:{all:[1.5,2.2]},kind:'range',
 high:'High A/G is rarely a concern.',
 low:'Low A/G means either low albumin or high globulin — usually inflammation.',
 levers:'Follow the component that is off.'},
/* ---------------- KIDNEY ---------------- */
{id:'bun',name:'BUN',cat:'kidney',unit:'mg/dL',alt:{'mmol/L':2.801},
 aliases:['BUN','Blood Urea Nitrogen','Urea Nitrogen'],
 std:{all:[6,24]},opt:{all:[10,20]},kind:'range',
 high:'High BUN in a lifter is usually high protein intake and mild dehydration, not kidney disease — check creatinine and eGFR alongside.',
 low:'Low BUN can mean low protein intake or liver issues.',
 levers:'Hydration, protein load before the draw.'},
{id:'creatinine',name:'Creatinine',cat:'kidney',unit:'mg/dL',alt:{'µmol/L':0.01131},
 aliases:['Creatinine, Serum','Creatinine'],
 std:{m:[0.76,1.27],f:[0.57,1.00]},opt:{m:[0.8,1.2],f:[0.6,1.0]},kind:'range',
 high:'Creatinine scales with muscle mass and creatine use, so muscular people run high without kidney trouble. Cystatin C is the cleaner check.',
 low:'Low creatinine reflects low muscle mass.',
 levers:'Hydration, creatine supplementation (raises it harmlessly), muscle mass; confirm with cystatin C if concerned.'},
{id:'egfr',name:'eGFR',cat:'kidney',unit:'mL/min/1.73',
 aliases:['eGFR','GFR, Estimated','Estimated GFR','GFR'],
 std:{all:[60,9999]},opt:{all:[90,9999]},kind:'higher',
 high:'Higher is better.',
 low:'eGFR is calculated from creatinine, so muscular or creatine-using people get artificially low numbers. Below 60 that persists needs a nephrologist.',
 levers:'Hydration, blood pressure, glucose control; recheck with cystatin C-based eGFR.'},
{id:'bun_cr',name:'BUN / Creatinine ratio',cat:'kidney',unit:'',
 aliases:['BUN/Creatinine Ratio','BUN/Creatinine','BUN/Creat Ratio'],
 std:{all:[9,20]},opt:{all:[10,18]},kind:'range',
 high:'High ratio is most often dehydration or high protein intake.',
 low:'Low ratio can reflect low protein intake or high muscle mass raising creatinine.',
 levers:'Hydration and protein timing.'},
{id:'cystatin',name:'Cystatin C',cat:'kidney',unit:'mg/L',
 aliases:['Cystatin C','Cystatin-C'],
 std:{all:[0.53,0.95]},opt:{all:[0,0.9]},kind:'lower',
 high:'Cystatin C is independent of muscle mass — if it is high, kidney filtration truly is reduced.',
 low:'Lower is better.',
 levers:'Blood pressure, glucose, NSAID use, hydration.'},
/* ---------------- ELECTROLYTES & MINERALS ---------------- */
{id:'sodium',name:'Sodium',cat:'lytes',unit:'mmol/L',
 aliases:['Sodium, Serum','Sodium'],
 std:{all:[134,144]},opt:{all:[137,142]},kind:'range',
 high:'High sodium is almost always dehydration at the draw.',
 low:'Low sodium can come from over-hydration, some medications, or heavy sweating without replacement.',
 levers:'Hydration and electrolyte intake around training.'},
{id:'potassium',name:'Potassium',cat:'lytes',unit:'mmol/L',
 aliases:['Potassium, Serum','Potassium'],
 std:{all:[3.5,5.2]},opt:{all:[4.0,4.8]},kind:'range',
 high:'High potassium can be a hemolyzed sample (very common) — or kidney/medication related if it repeats.',
 low:'Low potassium shows up as cramps, weakness and arrhythmia risk; diuretics and heavy sweating drive it.',
 levers:'Potassium-rich foods, magnesium status, diuretic review.'},
{id:'chloride',name:'Chloride',cat:'lytes',unit:'mmol/L',
 aliases:['Chloride, Serum','Chloride'],
 std:{all:[96,106]},opt:{all:[98,104]},kind:'range',
 high:'Usually dehydration or metabolic acidosis.',low:'Usually vomiting, over-hydration or alkalosis.',levers:'Hydration and acid-base balance.'},
{id:'co2',name:'CO2 (Bicarbonate)',cat:'lytes',unit:'mmol/L',
 aliases:['Carbon Dioxide, Total','Carbon Dioxide','CO2, Total','CO2','Bicarbonate'],
 std:{all:[20,29]},opt:{all:[23,28]},kind:'range',
 high:'High CO2 suggests metabolic alkalosis — often diuretics or vomiting.',
 low:'Low CO2 suggests acidosis — very low-carb diets, heavy training, kidney issues.',
 levers:'Diet acid load, hydration, kidney function.'},
{id:'calcium',name:'Calcium',cat:'lytes',unit:'mg/dL',alt:{'mmol/L':4.008},
 aliases:['Calcium, Serum','Calcium'],
 std:{all:[8.7,10.2]},opt:{all:[9.2,10.0]},kind:'range',
 high:'High calcium needs a parathyroid check, especially if repeated; high vitamin D dosing can contribute.',
 low:'Low calcium often tracks with low albumin or vitamin D deficiency.',
 levers:'Vitamin D and K2 status, parathyroid function, albumin correction.'},
{id:'magnesium',name:'Magnesium',cat:'lytes',unit:'mg/dL',alt:{'mmol/L':2.431},
 aliases:['Magnesium, Serum','Magnesium'],
 std:{all:[1.6,2.3]},opt:{all:[2.0,2.3]},kind:'range',
 high:'High serum magnesium is rare outside kidney disease or heavy supplementation.',
 low:'Serum magnesium is a poor reflection of tissue stores — low-normal usually means deficient. Cramps, poor sleep, arrhythmias.',
 levers:'Magnesium glycinate/citrate 300–500 mg, leafy greens, alcohol reduction; RBC magnesium is the better test.'},
{id:'rbc_mg',name:'Magnesium, RBC',cat:'lytes',unit:'mg/dL',
 aliases:['Magnesium, RBC','RBC Magnesium','Magnesium RBC'],
 std:{all:[4.2,6.8]},opt:{all:[5.5,6.5]},kind:'range',
 high:'Rare; supplement-related.',low:'Low RBC magnesium confirms a true deficiency.',levers:'Magnesium supplementation, retest in 3 months.'},
{id:'phos',name:'Phosphorus',cat:'lytes',unit:'mg/dL',alt:{'mmol/L':3.097},
 aliases:['Phosphorus, Serum','Phosphorus','Phosphate'],
 std:{all:[2.8,4.1]},opt:{all:[3.0,4.0]},kind:'range',
 high:'High phosphorus points to kidney function or excess intake (processed foods, soda).',
 low:'Low phosphorus can come from refeeding, vitamin D deficiency or malabsorption.',
 levers:'Diet quality, vitamin D, kidney function.'},
/* ---------------- CBC ---------------- */
{id:'wbc',name:'WBC',cat:'cbc',unit:'x10E3/µL',
 aliases:['WBC','White Blood Cell Count','White Blood Cells','Leukocytes'],
 std:{all:[3.4,10.8]},opt:{all:[4.0,7.0]},kind:'range',
 high:'High WBC means the immune system is active — infection, inflammation, stress, smoking, or a recent hard session.',
 low:'Low WBC can be benign (ethnic variation) or reflect immune suppression, nutrient deficiency, or overtraining.',
 levers:'Sleep, training recovery, infection status, smoking.'},
{id:'rbc',name:'RBC',cat:'cbc',unit:'x10E6/µL',
 aliases:['RBC','Red Blood Cell Count','Red Blood Cells','Erythrocytes'],
 std:{m:[4.14,5.80],f:[3.77,5.28]},opt:{m:[4.5,5.5],f:[4.0,5.0]},kind:'range',
 high:'High RBC (with high hematocrit) is common on TRT and at altitude; thick blood raises clot risk.',
 low:'Low RBC is anemia — iron, B12, folate, or blood loss.',
 levers:'TRT dose/frequency, hydration, donation when hematocrit is high; iron/B12 when low.'},
{id:'hgb',name:'Hemoglobin',cat:'cbc',unit:'g/dL',alt:{'g/L':0.1},
 aliases:['Hemoglobin','Haemoglobin','HGB','Hgb'],
 std:{m:[13.0,17.7],f:[11.1,15.9]},opt:{m:[14.0,17.0],f:[12.5,15.0]},kind:'range',
 high:'High hemoglobin tracks with hematocrit — TRT, dehydration, altitude, sleep apnea.',
 low:'Low hemoglobin is anemia: fatigue, breathlessness, poor performance. Check ferritin and B12.',
 levers:'Iron/B12/folate status, TRT management, sleep apnea screening.'},
{id:'hct',name:'Hematocrit',cat:'cbc',unit:'%',
 aliases:['Hematocrit','Haematocrit','HCT','Hct'],
 std:{m:[37.5,51.0],f:[34.0,46.6]},opt:{m:[41,50],f:[37,45]},kind:'range',
 high:'Hematocrit above ~52–54% is the number to watch on TRT — increases clotting risk. Hydrate before the draw; it swings with fluid status.',
 low:'Low hematocrit is anemia — same workup as hemoglobin.',
 levers:'TRT dose and injection frequency, hydration, sleep apnea, therapeutic phlebotomy/donation when high.'},
{id:'mcv',name:'MCV',cat:'cbc',unit:'fL',
 aliases:['MCV','Mean Corpuscular Volume'],
 std:{all:[79,97]},opt:{all:[85,92]},kind:'range',
 high:'Large red cells (high MCV) suggest B12/folate deficiency, alcohol, or thyroid issues.',
 low:'Small red cells (low MCV) suggest iron deficiency or thalassemia trait.',
 levers:'B12/folate when high; iron when low; alcohol.'},
{id:'mch',name:'MCH',cat:'cbc',unit:'pg',
 aliases:['MCH','Mean Corpuscular Hemoglobin'],
 std:{all:[26.6,33.0]},opt:{all:[28,32]},kind:'range',
 high:'Tracks with high MCV.',low:'Tracks with low MCV — iron.',levers:'Follow MCV.'},
{id:'mchc',name:'MCHC',cat:'cbc',unit:'g/dL',
 aliases:['MCHC','Mean Corpuscular Hemoglobin Concentration'],
 std:{all:[31.5,35.7]},opt:{all:[32,35]},kind:'range',
 high:'High MCHC is uncommon; can reflect spherocytosis or a sample artifact.',low:'Low MCHC points to iron deficiency.',levers:'Iron status.'},
{id:'rdw',name:'RDW',cat:'cbc',unit:'%',
 aliases:['RDW','Red Cell Distribution Width'],
 std:{all:[11.6,15.4]},opt:{all:[0,13.5]},kind:'lower',
 high:'High RDW means red cells vary a lot in size — an early flag for iron, B12 or folate deficiency, and a general marker of physiologic stress.',
 low:'Lower is better.',
 levers:'Iron, B12, folate status; inflammation.'},
{id:'plt',name:'Platelets',cat:'cbc',unit:'x10E3/µL',
 aliases:['Platelets','Platelet Count','PLT'],
 std:{all:[150,450]},opt:{all:[175,300]},kind:'range',
 high:'High platelets accompany inflammation, iron deficiency, or recovery from illness.',
 low:'Low platelets can come from alcohol, some medications, viral illness, or liver issues.',
 levers:'Inflammation, iron, alcohol, medication review.'},
{id:'neut',name:'Neutrophils (abs)',cat:'cbc',unit:'x10E3/µL',
 aliases:['Neutrophils (Absolute)','Neutrophils Absolute','Absolute Neutrophils','Neutrophils, Absolute','Neutro Abs','Neutrophils'],
 std:{all:[1.4,7.0]},opt:{all:[1.8,5.0]},kind:'range',
 high:'High neutrophils suggest bacterial infection, inflammation, stress or steroids.',
 low:'Low neutrophils (neutropenia) is common and benign in some ancestries; otherwise consider viral illness, medications, deficiency.',
 levers:'Infection status, stress, medications.'},
{id:'lymph',name:'Lymphocytes (abs)',cat:'cbc',unit:'x10E3/µL',
 aliases:['Lymphs (Absolute)','Lymphocytes (Absolute)','Lymphocytes Absolute','Absolute Lymphocytes','Lymphs Abs','Lymphocytes','Lymphs'],
 std:{all:[0.7,3.1]},opt:{all:[1.2,3.0]},kind:'range',
 high:'High lymphocytes usually mean a viral infection or immune activation.',
 low:'Low lymphocytes reflect immune suppression — chronic stress, overtraining, cortisol, or illness.',
 levers:'Sleep, recovery, stress, nutrition.'},
{id:'mono',name:'Monocytes (abs)',cat:'cbc',unit:'x10E3/µL',
 aliases:['Monocytes(Absolute)','Monocytes (Absolute)','Monocytes Absolute','Absolute Monocytes','Monocytes'],
 std:{all:[0.1,0.9]},opt:{all:[0.2,0.6]},kind:'range',
 high:'High monocytes suggest chronic inflammation or recovery from infection.',low:'Rarely significant.',levers:'Inflammation.'},
{id:'eos',name:'Eosinophils (abs)',cat:'cbc',unit:'x10E3/µL',
 aliases:['Eos (Absolute)','Eosinophils (Absolute)','Eosinophils Absolute','Absolute Eosinophils','Eosinophils','Eos'],
 std:{all:[0.0,0.4]},opt:{all:[0.0,0.3]},kind:'lower',
 high:'High eosinophils point to allergies, asthma, or parasites.',low:'Not a concern.',levers:'Allergen exposure.'},
{id:'baso',name:'Basophils (abs)',cat:'cbc',unit:'x10E3/µL',
 aliases:['Baso (Absolute)','Basophils (Absolute)','Basophils Absolute','Absolute Basophils','Basophils','Basos'],
 std:{all:[0.0,0.2]},opt:{all:[0.0,0.1]},kind:'lower',
 high:'Rarely elevated; allergies or hypothyroidism.',low:'Not a concern.',levers:'—'},
/* ---------------- IRON ---------------- */
{id:'ferritin',name:'Ferritin',cat:'iron',unit:'ng/mL',alt:{'µg/L':1},
 aliases:['Ferritin, Serum','Ferritin'],
 std:{m:[30,400],f:[15,150]},opt:{m:[50,150],f:[40,120]},kind:'range',
 high:'Ferritin is also an inflammation marker — high values can be iron overload (hemochromatosis) or inflammation/fatty liver. Check iron saturation and CRP.',
 low:'Low ferritin is depleted iron stores — fatigue, poor endurance, hair shedding — well before anemia shows on the CBC.',
 levers:'Iron intake/absorption (with vitamin C, away from coffee), blood loss, donation when high, inflammation.'},
{id:'iron',name:'Iron',cat:'iron',unit:'µg/dL',alt:{'µmol/L':5.585},
 aliases:['Iron, Serum','Iron Serum','Iron'],
 std:{all:[38,169]},opt:{all:[70,140]},kind:'range',
 high:'Serum iron swings with recent meals and supplements; high with high saturation suggests overload.',
 low:'Low serum iron with low ferritin is deficiency; with normal ferritin it may be inflammation.',
 levers:'Fast before the draw, iron intake, absorption.'},
{id:'tibc',name:'TIBC',cat:'iron',unit:'µg/dL',
 aliases:['Iron Binding Capacity','Total Iron Binding Capacity','TIBC'],
 std:{all:[250,450]},opt:{all:[250,380]},kind:'range',
 high:'High TIBC means the body is hungry for iron — deficiency.',low:'Low TIBC accompanies iron overload or inflammation.',levers:'Iron status.'},
{id:'uibc',name:'UIBC',cat:'iron',unit:'µg/dL',
 aliases:['UIBC','Unsaturated Iron Binding Capacity'],
 std:{all:[111,343]},opt:{all:[150,300]},kind:'range',
 high:'High UIBC tracks with iron deficiency.',low:'Low UIBC tracks with iron overload.',levers:'Iron status.'},
{id:'iron_sat',name:'Iron Saturation',cat:'iron',unit:'%',
 aliases:['Iron Saturation','Iron Sat','Transferrin Saturation','% Saturation','Saturation'],
 std:{all:[15,55]},opt:{all:[25,45]},kind:'range',
 high:'Saturation above ~45–50% on repeat is the screening flag for hemochromatosis.',
 low:'Low saturation is functional iron deficiency.',
 levers:'Iron intake, donation when high, genetic testing when persistently high.'},
/* ---------------- INFLAMMATION ---------------- */
{id:'hscrp',name:'hs-CRP',cat:'inflam',unit:'mg/L',
 aliases:['C-Reactive Protein, Cardiac','C-Reactive Protein,Cardiac','CRP, High Sensitivity','High Sensitivity CRP','hs-CRP','hsCRP','C-Reactive Protein','CRP'],
 std:{all:[0,3.0]},opt:{all:[0,1.0]},kind:'lower',
 high:'hs-CRP above 1 is low-grade systemic inflammation; above 3 is high cardiovascular risk. Recent illness, injury or a brutal workout spike it temporarily.',
 low:'Lower is better.',
 levers:'Body fat, sleep, omega-3s, gut health, dental health, alcohol; retest when healthy and rested.'},
{id:'homocysteine',name:'Homocysteine',cat:'inflam',unit:'µmol/L',
 aliases:['Homocyst(e)ine','Homocysteine'],
 std:{all:[0,15]},opt:{all:[0,9]},kind:'lower',
 high:'High homocysteine points to B12/folate/B6 shortfall or MTHFR variants, and raises cardiovascular risk.',
 low:'Lower is better.',
 levers:'Methylated B12 and folate, B6, TMG, creatine.'},
{id:'esr',name:'ESR',cat:'inflam',unit:'mm/hr',
 aliases:['Sedimentation Rate-Westergren','Sed Rate','Sedimentation Rate','ESR'],
 std:{m:[0,15],f:[0,32]},opt:{all:[0,10]},kind:'lower',
 high:'Elevated ESR is a slow-moving inflammation marker — infection, autoimmune activity, or anemia.',
 low:'Lower is better.',
 levers:'Address inflammation source.'},
/* ---------------- VITAMINS ---------------- */
{id:'vitd',name:'Vitamin D, 25-OH',cat:'vitamins',unit:'ng/mL',alt:{'nmol/L':0.4},
 aliases:['Vitamin D, 25-Hydroxy','Vitamin D,25-OH,Total','Vitamin D 25-Hydroxy','25-Hydroxy Vitamin D','25-OH Vitamin D','Vitamin D, 25-OH','Vitamin D 25-OH','Vitamin D (25-OH)','Vit D 25-OH','Vitamin D'],
 std:{all:[30,100]},opt:{all:[50,80]},kind:'range',
 high:'Above 100 means over-supplementation; toxicity is rare but calcium should be checked.',
 low:'Low vitamin D is nearly universal indoors — immune function, testosterone support, bone, mood.',
 levers:'Sun exposure, D3 2,000–5,000 IU with K2 and fat, retest in 3 months.'},
{id:'b12',name:'Vitamin B12',cat:'vitamins',unit:'pg/mL',alt:{'pmol/L':1.355},
 aliases:['Vitamin B-12','Vitamin B12','B-12','B12','Cobalamin'],
 std:{all:[232,1245]},opt:{all:[500,1000]},kind:'range',
 high:'High B12 is usually supplementation; unexplained highs deserve a liver/kidney check.',
 low:'Low-normal B12 still causes fatigue, brain fog and nerve symptoms — especially on metformin, PPIs, or plant-based diets.',
 levers:'Methylcobalamin, animal protein, absorption (PPIs, metformin).'},
{id:'folate',name:'Folate',cat:'vitamins',unit:'ng/mL',alt:{'nmol/L':0.4413},
 aliases:['Folate (Folic Acid), Serum','Folate, Serum','Folic Acid','Folate'],
 std:{all:[3.0,9999]},opt:{all:[10,9999]},kind:'higher',
 high:'Higher is fine within reason; very high with low B12 can mask a B12 problem.',
 low:'Low folate drives high homocysteine, fatigue and anemia.',
 levers:'Leafy greens, methylfolate.'},
{id:'zinc',name:'Zinc',cat:'vitamins',unit:'µg/dL',
 aliases:['Zinc, Plasma or Serum','Zinc, Serum','Zinc'],
 std:{all:[44,115]},opt:{all:[90,110]},kind:'range',
 high:'High zinc is supplementation — long-term high doses deplete copper.',
 low:'Low zinc undermines testosterone, immunity, skin and taste.',
 levers:'Red meat, oysters, zinc picolinate 15–30 mg (with copper if long-term).'},
/* ---------------- OTHER ---------------- */
{id:'psa',name:'PSA',cat:'other',unit:'ng/mL',
 aliases:['Prostate Specific Ag, Serum','Prostate Specific Antigen','PSA, Total','PSA'],
 std:{m:[0,4.0],f:null},opt:{m:[0,1.5],f:null},kind:'lower',
 high:'PSA rises with prostate size, infection, recent ejaculation/cycling, and on TRT. A jump of more than ~1.0 in a year matters more than the absolute number.',
 low:'Lower is better.',
 levers:'Avoid ejaculation/cycling 48h before the draw; track the trend on TRT.'},
{id:'ck',name:'Creatine Kinase (CK)',cat:'other',unit:'U/L',alt:{'IU/L':1},
 aliases:['Creatine Kinase,Total','Creatine Kinase, Total','Creatine Kinase','CK, Total','CPK','CK'],
 std:{m:[39,308],f:[26,192]},opt:{all:[0,250]},kind:'lower',
 high:'CK is muscle damage — every hard lifter runs it high after training. Values in the thousands with dark urine are an emergency (rhabdo).',
 low:'Not a concern.',
 levers:'Rest 72 hours before the draw; hydration.'},
{id:'ldh',name:'LDH',cat:'other',unit:'U/L',alt:{'IU/L':1},
 aliases:['LDH','Lactate Dehydrogenase','LD'],
 std:{all:[121,224]},opt:{all:[121,200]},kind:'range',
 high:'High LDH is non-specific tissue damage — muscle, liver, red cells (hemolyzed sample).',low:'Not a concern.',levers:'Training timing, sample quality.'},
{id:'omega3',name:'Omega-3 Index',cat:'other',unit:'%',
 aliases:['Omega-3 Index','Omega 3 Index','OmegaCheck'],
 std:{all:[4,9999]},opt:{all:[8,9999]},kind:'higher',
 high:'Higher is better up to ~12%.',low:'Below 4% is high cardiovascular risk; most Americans sit around 4–5%.',levers:'2–4 g EPA/DHA daily, fatty fish; retest in 4 months.'}
];
